# Use an empty string if you have multiple domain linking to your website
# This string is used to generate the absolute URL for your assets.
baseURL = 'https://catielleandressa.com'
defaultContentLanguage = 'en'
# Emoji in markdown files
enableEmoji = true
languageCode = 'en-us'
# Number of blog post per page
paginate = 10
theme = 'pico'
# Title of the website is used for the meta tag title
# and the square icon (not the favicon)
title = 'Catielle Andressa'

[params]
customCSS = [
	"style/style.css",
	"style/theme.sass",
] # Path relative to assets folder
customJS = ["js/console.js"] # Path relative to assets folder
# Homepage description
# For blog page description you can overwrite it 
# in the front matter
description = "Catielle Andressa | Writer and Storytelling Consultant"
email = "catielle@posteo.net"
favicon = '/icons/favicon.ico'
# Dark mode support
# Supported value are :
# - off
# - always
# If commented the theme will use the browser theme.
darkMode = 'off'

# Social parameters for contact_icons widget
[[params.social]]
alt = "medium icon"
blank = true
icon = "/icons/medium.png"
name = "medium"
url = "https://medium.com/@catielle"

[[params.social]]
alt = "instagram icon"
icon = "/icons/instagram.png"
name = "instagram"
url = "https://instagram.com/catcreatestories"

[[params.social]]
alt = "linkedin icon"
icon = "/icons/linkedin.png"
name = "linkedin"
url = "https://www.linkedin.com/in/catielleandressa"

[[params.social]]
alt = "pinterest icon"
icon = "/icons/pinterest.png"
name = "pinterest"
url = "https://www.pinterest.it/catiellean/"


# Navigation bar
[menu]

[[menu.main]]
identifier = "home" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/" 
weight = 10 

[[menu.main]]
identifier = "contact" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/#contact" 
weight = 30 

# Syntax highlightning
[markup.highlight]
guessSyntax = true 
lineNumbersInTable = true 
noClasses = false # Set to false to use the Pico default theme.
tabWidth = 2 

[taxonomies]
category = "categories"
tag = "tags"

# Translation
# English, French and Italian are supported but you can contribute
# by adding translation to i18n/ folder.
[languages.en]
contentDir = 'content/en'
languageCode = 'en'
languageName = 'English'
weight = 0
description = "Catielle Andressa | Writer and Screenwriter"
[languages.ita]
contentDir = 'content/ita'
languageCode = 'ita'
languageName = 'Italiano'
weight = 2
description = "Catielle Andressa | Scrittricce e Consulente di Stoytelling"
